### ISSUE TITLE
a specific type of bus is not visible on bkk-stop-card

### ISSUE THREAD

**Issue by lancusfpv** [amaximus/bkk-stop-card#1]
I am using the following in configuration.yaml

 - platform: bkk_stop
    name: 'bkk_67-bus'
    stopId: 'BKK_F03556'
    minsAfter: 50
    wheelchair: true
    ignoreNow: true

and this in the custom card configuration:

entity: sensor.bkk_67-bus
type: 'custom:bkk-stop-card'

The card cannot show the detail. It only gives this error:
Undefined
No service to any destination in following mins

Please help, thank you!

**Comment by amaximus** [comment]
Please invert the order of the type and entity lines and reload the page.

Please get back to me with results.

**Comment by lancusfpv** [comment]
Tried to change the order. Same result.

**Comment by amaximus** [comment]
Tried to reproduce the issue.
Please note that the entity name should be bkk_67_bus. HASS converts - into _ to keep sensor names within word boundaries.
You may check the name of the sensor in the Developer section under States.

![capture_09122019_160404](https://user-images.githubusercontent.com/2511168/64791288-cc7bca00-d577-11e9-83e9-49ee24203a20.jpg)

So in the ui-lovelace.yaml refer to sensor.bkk_67_bus .

**Comment by lancusfpv** [comment]
its working indeed. Thanks for your quick help!
