### ISSUE TITLE
In-mins parameter calculation from predicted times

### ISSUE THREAD

**Issue by bvermes17** [amaximus/bkk-stop-card#12]
Dear @amaximus , 

Would it be somehow possible to set the card to calculate the in-mins time from the predicted times when they are available? Currently if in-mins is set to true, it calculates from the scheduled at-time not considering a predicted delay if its available. Also the BKK GO layout works the same, if there is a delay it will not show it in the remaining minutes table. 

I am using this integration for Train schedules (when to start heading to the station). Would be great if this could be set up somehow. 

Thanks!

**Comment by amaximus** [comment]
This is not a UI stuff, but custom integration one.
The newest release of the bkk_stop custom integration adds this support.
Please see: https://github.com/amaximus/bkk_stop/releases/tag/2.5.0

Please update the custom integration, adjust the sensor configuration and get back to me with results.

**Comment by amaximus** [comment]
Did you manage to update and test the latest version of the custom integration supporting the in-mins based on predicted time?

**Comment by bvermes17** [comment]
Dear @amaximus !

I tested it and it works perfectly! Thank you! :)
