### ISSUE TITLE
bkk cards are empty

### ISSUE THREAD

**Issue by hoboristi** [amaximus/bkk-stop-card#2]
I have followed your instructuctions related to lovelace config, but the cards are showing this:
![bkk](https://user-images.githubusercontent.com/4062730/71784603-6bc83f80-2ff5-11ea-8165-05da17f504fb.PNG)

Also, the plugins itself works..

**Comment by amaximus** [comment]
Could you please post the config of one of the related bkk sensors?

**Comment by hoboristi** [comment]
Sure, here is the sensor config at configuration.yaml:
  - platform: bkk_stop
    name: 1_home-Arpad_hid
    stopId: 'BKK_F02631'

  - platform: bkk_stop
    name: M2_Arpad_hid-Gyongyosi
    stopId: 'BKK_F02637'

And there is the lovelace:
  - url: /local/community/bkk-stop-card/bkk-stop-card.js
    type: module

  - title: BKK
    icon: mdi:car-multiple
    cards:
      - type: custom:bkk-stop-card
        entity: sensor.1_home-Arpad_hid
      - type: custom:bkk-stop-card
        entity: sensor.M2_Arpad_hid-Gyongyosi

**Comment by amaximus** [comment]
In the lovelace-ui.yaml please replace the dashes with underscores for the bkk-stop-card entities sensor names.
You may check the sensor names on HA webUI->Developer tools->States page.
HA generates the sensor names to comply with string boundaries.

Please get back to me with results.

**Comment by hoboristi** [comment]
Hi there,

Finally I found the problem, there were capital letters in my lovelace config as it can be seen, it caused the problem.
