### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by laszlojakab** [amaximus/bkk-stop-card#3]
If I open a tab in HA where BKK stop card inserted my whole browser (almost) freeze. I profiled the running code and it seems that _getAttributes function takes about 3 seconds to run. Updating of hass object is takes more than once in 3 seconds so thats causes to freeze of the browser. As I checked the code there are nested forEach calls on state and attribute keys. I've printed out and I have a fairly large amount of states (approx 2500) and attributes (approx 10000) in HA. Could you modify the code to work with that large amount of states/attributes?

**Comment by amaximus** [comment]
Thanks for the heads up on performance issue.

The card and the related custom integration have been completely rewritten.
Please update both and get back to me with results.

**Comment by laszlojakab** [comment]
Problem solved in new version. Performance is okay now. Thank you for your fast response.
