### ISSUE TITLE
[feature request] Renaming stops displayed on the card

### ISSUE THREAD

**Issue by pvojnisek** [amaximus/bkk-stop-card#4]
I would like to rename the stop displayed on lovelace.

For example: Bem tábornok utca --> Bem stop

![bkk_stop Lovelace example](https://raw.githubusercontent.com/amaximus/bkk_stop/master/example/bkk_lovelace.jpg)

The `name` attribute could be used in the yaml like this:
```
type: custom:bkk-stop-card
entity: sensor.bkk_bem
name: Bem stop
```

**Comment by amaximus** [comment]
Newest version of the card (1.0.0) adds a new optional configuration parameter, `name` that, if set, will overwrite the card title/stattion name.

Please update the card and get back to me with results

**Comment by pvojnisek** [comment]
It works as expected! Thank you for the fast implementation! :)
