### ISSUE TITLE
[bug] wrong object (routeobjarray)

### ISSUE THREAD

**Issue by sipimokus** [amaximus/bkk-stop-card#5]
While I tested my changes for [integration](https://github.com/amaximus/bkk_stop/issues/13), I found this error in this lovelace card.
https://github.com/amaximus/bkk-stop-card/blob/master/bkk-stop-card.js#L47

The `routeobjarray` it's bad, I think the good variable is a `res`.

**Comment by amaximus** [comment]
Thanks for the heads-up.
Newer version (1.0.1) fixes the issue.
Please check on your side too and get back to me with results.

**Comment by sipimokus** [comment]
I tested, its works well. Thank you!
