### ISSUE TITLE
[feature request] Filter to specific BUS 

### ISSUE THREAD

**Issue by GMFalka** [amaximus/bkk-stop-card#9]
Hello!

Would like to see a "filter" feature to show only certain buses

Usually i only need 1 bus from the specified station, but 5-10 different busses are shown

**Comment by amaximus** [comment]
I added support for route_id filtering on sensor level (https://github.com/amaximus/bkk_stop/releases/tag/2.4.0) .
Please update the custom integration and get back to me with results.
